# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='vector',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vector',
            field=models.BinaryField(null=True),
        ),
    ]
