# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_auto_20180309_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='vector_needs_synch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vector_needs_synch',
            field=models.BooleanField(default=True),
        ),
    ]
